/* ==========================================================================
   REFERENCE DATA — Handbook & Glossary
   ========================================================================== */

const HANDBOOK_DATA = [
  {title:'Solar System', icon:'orbit',
   body:'The Solar System consists of the Sun and everything bound to it by gravity: eight planets, five recognised dwarf planets, hundreds of moons, and countless asteroids and comets. It formed about 4.6 billion years ago from a collapsing cloud of gas and dust.',
   points:['Inner rocky planets: Mercury, Venus, Earth, Mars.','Outer gas & ice giants: Jupiter, Saturn, Uranus, Neptune.','The asteroid belt lies between Mars and Jupiter.','Everything orbits the Sun in roughly the same flat plane, the ecliptic.']},
  {title:'Stars', icon:'star',
   body:'Stars are enormous spheres of hydrogen and helium held together by gravity, generating energy through nuclear fusion in their cores. Our Sun is a fairly average, middle-aged star.',
   points:['Star colour reveals surface temperature: blue is hottest, red is coolest.','Brightness as seen from Earth is called apparent magnitude.','Stars are born in nebulae and eventually exhaust their fuel.','Massive stars can end their lives as supernovae, neutron stars, or black holes.']},
  {title:'Galaxies', icon:'galaxy',
   body:'A galaxy is a vast, gravitationally bound collection of stars, gas, dust, and dark matter. Our home galaxy, the Milky Way, contains an estimated 100–400 billion stars.',
   points:['Spiral galaxies have rotating arms of young, bright stars.','Elliptical galaxies are smooth, rounded, and made mostly of older stars.','Irregular galaxies have no defined shape, often due to gravitational interactions.','Galaxies cluster together across the universe, connected by cosmic filaments.']},
  {title:'Constellations', icon:'compass',
   body:'Constellations are patterns of stars that ancient cultures grouped together and named, often after animals, characters, or objects. The stars in a constellation are usually not physically related — they only appear close together from Earth.',
   points:['88 official constellations cover the entire sky today.','Circumpolar constellations never set below the horizon at certain latitudes.','Constellations have long been used for navigation and calendars.','The visible constellations change with the seasons as Earth orbits the Sun.']},
  {title:'Space Exploration', icon:'rocket',
   body:'Since the launch of Sputnik 1 in 1957, humans have sent robotic probes and crewed missions across the Solar System, deployed thousands of satellites, and built permanently crewed space stations in orbit.',
   points:['Artificial satellites enable communication, GPS, and weather forecasting.','Robotic rovers have driven across the surface of Mars.','The International Space Station orbits Earth roughly every 90 minutes.','Future missions aim to return humans to the Moon and eventually reach Mars.']},
  {title:'Telescopes', icon:'target',
   body:'Telescopes collect and focus light (or other radiation) to reveal objects too faint or distant to see with the naked eye. Optical telescopes use lenses or mirrors; radio, infrared, X-ray and gamma-ray telescopes reveal light invisible to our eyes.',
   points:['Refracting telescopes use lenses; reflecting telescopes use mirrors.','Larger apertures collect more light and resolve finer detail.','Space telescopes avoid the blurring effect of Earth\u2019s atmosphere.','Radio telescopes can detect signals from the earliest moments of the universe.']},
  {title:'Astronomical Units', icon:'chart',
   body:'Astronomers use special units because ordinary distances become unmanageable at cosmic scale.',
   points:['1 Astronomical Unit (AU) = average Earth–Sun distance ≈ 149.6 million km.','1 Light-year = distance light travels in a year ≈ 9.46 trillion km.','1 Parsec ≈ 3.26 light-years, used for measuring stellar distances.','Magnitude measures brightness — lower numbers mean brighter objects.']},
  {title:'Gravity', icon:'blackhole',
   body:'Gravity is the attractive force between any two masses. It holds planets in orbit, shapes galaxies, and governs the life cycle of stars. The more massive an object and the closer you are to it, the stronger its gravitational pull.',
   points:['Newton\u2019s law: gravitational force decreases with the square of distance.','Orbits are a balance between gravity pulling inward and velocity carrying an object forward.','Escape velocity is the speed needed to break free of a body\u2019s gravity.','Extremely dense objects like black holes have gravity so strong not even light escapes.']},
];

const GLOSSARY_DATA = [
  {term:'Aphelion', pron:'/uh-FEE-lee-uhn/', def:'The point in an orbit around the Sun that is farthest from the Sun.'},
  {term:'Asteroid', pron:'/AS-ter-oid/', def:'A small rocky body orbiting the Sun, most commonly found in the asteroid belt between Mars and Jupiter.'},
  {term:'Astronomical Unit (AU)', pron:'/ay-yoo/', def:'A unit of distance equal to the average distance between Earth and the Sun, about 149.6 million kilometres.'},
  {term:'Axial Tilt', pron:'', def:'The angle between a planet\u2019s rotation axis and its orbital plane; responsible for seasons.'},
  {term:'Black Hole', pron:'', def:'A region of space where gravity is so strong that nothing, not even light, can escape once past the event horizon.'},
  {term:'Comet', pron:'', def:'A small icy body that develops a glowing coma and tail when its orbit brings it close to the Sun.'},
  {term:'Eccentricity', pron:'', def:'A measure of how much an orbit deviates from a perfect circle; 0 is circular, closer to 1 is highly elongated.'},
  {term:'Eclipse', pron:'', def:'An event where one celestial body moves into the shadow of another, or passes between an observer and a light source.'},
  {term:'Ecliptic', pron:'', def:'The apparent path the Sun traces across the sky over a year, and the plane in which most planets orbit.'},
  {term:'Event Horizon', pron:'', def:'The boundary around a black hole beyond which nothing can escape its gravitational pull.'},
  {term:'Galaxy', pron:'', def:'A massive, gravitationally bound system of stars, gas, dust, and dark matter.'},
  {term:'Geostationary Orbit', pron:'', def:'A circular orbit above Earth\u2019s equator where a satellite\u2019s period matches Earth\u2019s rotation, keeping it over one spot.'},
  {term:'Gravity', pron:'', def:'The attractive force exerted by any object with mass on any other object with mass.'},
  {term:'Kepler\u2019s Laws', pron:'', def:'Three laws describing planetary motion: elliptical orbits, equal areas in equal times, and the relationship between orbital period and distance.'},
  {term:'Light-year', pron:'', def:'The distance light travels in one year, about 9.46 trillion kilometres — a unit of distance, not time.'},
  {term:'Lunar Eclipse', pron:'', def:'An event where Earth passes between the Sun and the Moon, casting its shadow on the Moon.'},
  {term:'Nebula', pron:'/NEB-yuh-luh/', def:'A vast cloud of gas and dust in space, often a stellar nursery where new stars are born.'},
  {term:'Orbit', pron:'', def:'The curved path a body follows around another body due to gravity.'},
  {term:'Parsec', pron:'', def:'A unit of astronomical distance equal to about 3.26 light-years.'},
  {term:'Penumbra', pron:'', def:'The lighter, outer part of a shadow where only part of a light source is blocked.'},
  {term:'Perihelion', pron:'/pair-ih-HEE-lee-uhn/', def:'The point in an orbit around the Sun that is closest to the Sun.'},
  {term:'Revolution', pron:'', def:'The motion of a body travelling around another body, such as Earth orbiting the Sun.'},
  {term:'Rotation', pron:'', def:'The spinning motion of a body around its own axis.'},
  {term:'Satellite', pron:'', def:'Any object that orbits another, natural (like the Moon) or artificial (like a communications satellite).'},
  {term:'Solar Eclipse', pron:'', def:'An event where the Moon passes between the Sun and Earth, blocking some or all of the Sun\u2019s light.'},
  {term:'Solstice', pron:'', def:'The two moments each year when a hemisphere is tilted most toward or away from the Sun, producing the longest or shortest day.'},
  {term:'Umbra', pron:'', def:'The darkest, central part of a shadow where the light source is completely blocked.'},
  {term:'Escape Velocity', pron:'', def:'The minimum speed needed for an object to break free of a body\u2019s gravitational pull without further propulsion.'},
  {term:'Equinox', pron:'', def:'The two moments each year when day and night are approximately equal in length everywhere on Earth.'},
  {term:'Waxing / Waning', pron:'', def:'Terms describing whether the Moon\u2019s illuminated portion is increasing (waxing) or decreasing (waning).'},
];
