/* ==========================================================================
   VEC.GLOSSARY — illustrated glossary term bank
   ========================================================================== */
window.VEC_GLOSSARY = [
  { term:'Demand', pron:'/dɪˈmɑːnd/', def:'The quantity of a good or service consumers are willing and able to buy at various prices over a given period.', example:'A fall in the price of rice increases the quantity of rice demanded.' },
  { term:'Supply', pron:'/səˈplaɪ/', def:'The quantity of a good or service producers are willing and able to offer for sale at various prices.', example:'A bumper wheat harvest increases the supply of wheat in the market.' },
  { term:'Equilibrium Price', pron:'', def:'The price at which quantity demanded exactly equals quantity supplied, clearing the market.', example:'If demand and supply curves cross at ₹40, that is the equilibrium price.' },
  { term:'Shortage', pron:'', def:'A situation where quantity demanded exceeds quantity supplied at the current price, usually because price is set below equilibrium.' },
  { term:'Surplus', pron:'', def:'A situation where quantity supplied exceeds quantity demanded at the current price, usually because price is set above equilibrium.' },
  { term:'Price Ceiling', pron:'', def:'A government-imposed maximum legal price; if set below equilibrium, it creates a shortage.', example:'Rent control laws capping monthly rent.' },
  { term:'Price Floor', pron:'', def:'A government-imposed minimum legal price; if set above equilibrium, it creates a surplus.', example:'Minimum Support Price (MSP) for crops in India.' },
  { term:'Consumer Surplus', pron:'', def:'The difference between what consumers are willing to pay and what they actually pay.' },
  { term:'Producer Surplus', pron:'', def:'The difference between what producers actually receive and the minimum they would have accepted.' },
  { term:'Inflation', pron:'', def:'A sustained rise in the general price level of goods and services in an economy over time.', example:'India\'s CPI inflation is tracked monthly by the government.' },
  { term:'Deflation', pron:'', def:'A sustained fall in the general price level, often associated with weak demand.' },
  { term:'Purchasing Power', pron:'', def:'The value of money expressed in terms of the quantity of goods and services it can buy; inflation erodes it.' },
  { term:'Money Supply', pron:'', def:'The total stock of money (currency plus bank deposits) circulating in an economy at a point in time.' },
  { term:'Repo Rate', pron:'', def:'The interest rate at which the Reserve Bank of India lends short-term funds to commercial banks; a key inflation-control tool.' },
  { term:'Cash Reserve Ratio (CRR)', pron:'', def:'The minimum percentage of deposits banks must hold as reserves (not lent out), set by the central bank.' },
  { term:'Money Multiplier', pron:'', def:'The maximum amount of money the banking system can create from an initial deposit, equal to 1 ÷ reserve ratio.' },
  { term:'Non-Performing Asset (NPA)', pron:'', def:'A bank loan on which the borrower has stopped making interest or principal repayments.' },
  { term:'Gross Domestic Product (GDP)', pron:'', def:'The total market value of all final goods and services produced within a country in a given year.' },
  { term:'Per Capita Income', pron:'', def:'National income divided by population — an average measure of income per person.' },
  { term:'Fiscal Deficit', pron:'', def:'The gap between a government\'s total expenditure and its total revenue (excluding borrowing), financed by borrowing.' },
  { term:'Direct Tax', pron:'', def:'A tax paid directly to the government by the person or entity on whom it is levied, such as income tax.' },
  { term:'Indirect Tax', pron:'', def:'A tax collected by an intermediary (like a seller) from the person who bears the burden, such as GST.' },
  { term:'Progressive Tax', pron:'', def:'A tax whose effective rate rises as income rises.' },
  { term:'Regressive Tax', pron:'', def:'A tax whose effective burden, as a share of income, falls as income rises — common with indirect taxes.' },
  { term:'Tariff', pron:'', def:'A tax imposed on imported goods, raising their price to protect domestic producers and raise government revenue.' },
  { term:'Trade Balance', pron:'', def:'The difference between the value of a country\'s exports and imports; positive means a trade surplus, negative a trade deficit.' },
  { term:'Exchange Rate', pron:'', def:'The price of one currency expressed in terms of another, determining import/export competitiveness.' },
  { term:'Free Trade Agreement (FTA)', pron:'', def:'A pact between countries to reduce or remove tariffs and other trade barriers between them.' },
  { term:'Opportunity Cost', pron:'', def:'The value of the next best alternative given up when a choice is made.' },
  { term:'Engel\'s Law', pron:'', def:'The economic observation that the percentage of income spent on food falls as household income rises.' },
  { term:'Entrepreneurship', pron:'', def:'The process of designing, launching and running a new business, typically involving risk-taking and innovation.' },
  { term:'Fixed Cost', pron:'', def:'A business cost that does not change with the level of output in the short run, such as rent or salaries.' },
  { term:'Variable Cost', pron:'', def:'A business cost that rises and falls directly with the level of output, such as raw materials.' },
  { term:'Profit', pron:'', def:'The financial gain of a business, calculated as total revenue minus total cost.' },
  { term:'Subsidy', pron:'', def:'Financial assistance from the government to producers or consumers, lowering the effective cost of a good or input.' },
  { term:'Deadweight Loss', pron:'', def:'The loss of economic efficiency that occurs when the equilibrium outcome is not achieved, often due to taxes or price controls.' },
  { term:'Comparative Advantage', pron:'', def:'The ability of a country or producer to produce a good at a lower opportunity cost than others, forming the basis for beneficial trade.' },
];
